name: wine-analysis
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: iterative/setup-cml@v1
      - uses: action/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          pip install -r requirements.txt
          python train.py
          echo "## Feature Importance" >> report.md
          echo '![](./feature_importance.png "Feature Importance")' >> report.md
          echo "## Model Metrics" >> report.md
          cat metrics.txt >> report.md
          cml comment create report.md

          
 
          # Create CML report
          #cat metrics.txt >> report.md
          #echo '![](./plot.png "Confusion Matrix")' >> report.md
         # cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
